project:
  type: website

website:
  title: "L. Polyedra"
  navbar:
    left:
      - about.qmd
    right:
      - href: methods.qmd
        text: Methods
      - href: map.qmd
        text: Map

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true