project:
  type: website

website:
  title: "L. Polyedra"
  navbar:
    left:
      - href: https://aarongaines.github.io/
        text: Home
      - about.qmd
    right:
      - href: methods.qmd
        text: Methods
      - href: map.qmd
        text: Map


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true