---
title: "Methods"

---
This page is a work-in-progress.

## Detection

### Data
1. JAXA GCOM-C SGLI Satellite
    - Level 2 normalized water leaving radiance | NWLR: 380nm, 443nm
    - Level 2 chlorophyll-a concentration | IWPR: CHLA

### Methods

The algae bloom detection algorithm is based on the work of [Kahru et al. 2021](https://doi.org/10.1525/elementa.2020.00157) and implemented in Python using a combination of the rasterio and GDAL packages. With data from the GCOM-C satellite, the algorithm identifies algae blooms by comparing the remote sensing reflectance ($R_{rs}$) of the 380nm (UV) and 443nm (blue) bands, and the chlorophyll-a concentration ($Chla$) of the ocean surface. The algorithm identifies a bloom by the expression below:
$$\left( \frac{R_{rs}380nm}{R_{rs}443nm} \lt 1 \right){~and~} \left( {~Chla~} \gt 2mg/l \right)$$

This method relies on the fact that the L. polyedra algae produces a host of mycosporine-like amino acids (MAAs) that absorb UV light, while also producing chlorophyll-a. The MAAs absorb UV light, which reduces the $R_{rs}$ of the 380nm band, while the chlorophyll-a increases the $R_{rs}$ of the 443nm band. This results in a ratio, $\frac{R_{rs}380nm}{R_{rs}443nm}$, of less than 1 being useful for indicating L. polyedra algae blooms. We also know that L. polyedra blooms have a chlorophyll-a concentration greater than 1-2mg per liter, so we use a second threshold from a different dataset to help reduce false positives in the detection.

There are some issues with this methodology however. While L. polyedra is a producer of MAAs, it is not the only source of MAAs in the ocean even when it comes to other types of algae. Currently, this method is more an of indicator of dinoflagellate blooms in general, and L. polyedra happens to be the dominant species off of the Southern California coastline. It is recommended that this method be used in conjunction with in-situ measurements to verify the presence of L. polyedra, as the dominant species may change overtime. The [HABMAP](https://calhabmap.org/) program is a source for in-situ measurements, however there are only a few points in Southern California where measurements are taken.

One way to improve this method would be to find a UV band that is absorbed by the MAAs produced by L. polyedra, but not by other algae. This would require more research, and other UV bands at useful resolutions are not currently available from any satellite. This will change when the [NASA PACE](https://pace.gsfc.nasa.gov/) satellite is launched in early 2024. This satellite will have more UV bands avaliable which which may help to differentiate.

While this would improve accuracy in detecting the prescence of L. polyedra aglae, it would not neccesarily help with detecting actual bioluminescence. This is because the MAAs produced by L. polyedra are not the source of the bioluminescence. The bioluminescence is produced by the dinoflagellate's luciferin-luciferase reaction. This reaction is triggered by mechanical stress, such as the breaking of waves. This means that the bioluminescence is not always visible even when the algae is present. 


## Forecasting

### Data
1. Target Data
    - Daily/period of bloom detections
2. Predictors
    - Sea Surface Temperature
    - Air Temperature
    - Cummulative Precipitation
    - more...